### ISSUE TITLE
Improve documentation around NoWithVeto

### ISSUE THREAD

**Issue by ebuchman** [cosmos/governance#26]
NoWithVeto activity on Prop47 suggests we should do a better job of educating about what this option means  (it's a bit nuclear). 

Wrote some notes here: https://forum.cosmos.network/t/47-parameter-change-lower-minimum-proposal-deposit-amount/4792/7?u=ebuchman

There should probably be a page in the repo dedicated to the Voting options and explaining each one. It seems NoWithVeto isn't even mentioned at all in this repo which is obviously an oversight

**Comment by hxrts** [comment]
copying @sunnya97's comment for context:

> The purpose of NoWithVeto was set in Proposal #6 https://www.mintscan.io/cosmos/proposals/6
> "If a proposal seems to be spam or is deemed to have caused a negative externality to Cosmos community, voters should vote NoWithVeto on the proposal."

not sure how we want to resolve this semantic gap. perhaps we can discuss here.
