### ISSUE TITLE
Add CODEOWNERS with primary maintainers

### ISSUE THREAD

**Issue by dcwalk** [cosmos/governance#35]
Reticketed from #31, we were discussing making clear who to ping for review, but perhaps better to use existing patterns: 

> Also unclear if adding who to request review from is required, as perhaps better to set CODEOWNERS as you do in gaia: https://github.com/cosmos/gaia/blob/main/.github/CODEOWNERS

**Comment by hxrts** [comment]
Good idea. Right now I think @ebuchman @shahankhatch @zmanian and me have been most active to date. We can probably start there.
